export const musics = [ 
  {
    id:0,
    name: "Yaad aa rhi hai",
    song: "/music/Yaad-aa-rhi-hai.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:1,
    name: 'Ae gujarne waali hwa',
    song:"/music/Ae-gujarne-waali-hwa.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:2,
    name: "All is well",
    song: "/music/All-is-well.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:3,
    name: "Badan pe sitare lapete hue",
    song: "/music/Badan-pe-sitare-lapete-hue.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:4,
    name: "Bande hai hm uske",
    song: "/music/Bande-hai-hm-uske.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:5,
    name: "Behti hwa sa tha wo",
    song: "/music/Behti-hwa-sa-tha-wo.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:6,
    name: "Bella ciao",
    song: "/music/Bella-ciao.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:7,
    name: "Bella ciao hindi",
    song: "/music/Bella-ciao-hindi.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:8,
    name: "Desh mere",
    song: "/music/Desh-mere.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:9,
    name: "Give me some",
    song: "/music/Give-me-some.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:10,
    name: "Gori tori chunari",
    song: "/music/Gori-tori-chunari.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:11,
    name: "Haal kya hai dilon ka",
    song: "/music/Haal-kya-hai-dilon-ka.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:12,
    name: "Hai zindgi kitni khubsurat",
    song: "/music/Hai-zindgi-kitni-khubsurat.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:13,
    name: "Hey ram",
    song: "/music/Hey-ram.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:14,
    name: "Kamata hum bahut kuchh pr",
    song: "/music/Kamata-hum-bahut-kuchh-pr.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:15,
    name: "Kehdun tumhe ya chup rhun",
    song: "/music/Kehdun-tumhe-ya-chup-rhun.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:16,
    name: "Log kehte hain mai sarabi hun",
    song: "/music/Log-kehte-hain-mai-sarabi-hun.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:17,
    name: "Dhire dhire meri jindgi me aana",
    song: "/music/Dhire-dhire-meri-jindgi-me-aana.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:18,
    name: "Mere umar k nav jawaano",
    song: "/music/Mere-umar-k-nav-jawaano.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:19,
    name: "Peele peele o mere raaja",
    song: "/music/Peele-peele-o-mere-raaja.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
  {
    id:20,
    name: "Tu cheez bdi hai mast",
    song: "/music/Tu-cheez-bdi-hai-mast.mp3",
    singer: "Rahul Gandhi",
    language:"hindi",
  },
]